import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "./assets";
import { ChevronDown } from "lucide-react";

const accordionItems = [
  {
    value: "item-1",
    icon: "💰",
    title: "Investor Dividends",
    content:
      "The only project that shares a percentage of all profits generated by the app, toys, songs, and the MonkyLand ecosystem.",
  },
  {
    value: "item-2",
    icon: "🔥",
    title: "Burning of Unsold Tokens",
    content:
      "The same percentage is burned across all categories, reducing supply and increasing token value.",
  },
  {
    value: "item-3",
    icon: "👥",
    title: "Referral System",
    content:
      "Earn 10% in the same currency for each purchase made through your link, with instant withdrawals.",
  },
  {
    value: "item-4",
    icon: "🤖",
    title: "The First AI-Powered Educational Tutor",
    content:
      "Adapts to each child’s age, teaching values, motivation, and confidence in a safe, ad-free environment, featuring an app, toys, YouTube, and an educational metaverse.",
  },
  {
    value: "item-5",
    icon: "🌍",
    title: "Real Impact",
    content:
      "MonkyLand will help millions of children access an innovative, high-quality education worldwide.",
  },
  {
    value: "item-6",
    icon: "🚀",
    title: "A Token with Real-World Utility & Sustainable Growth",
    content: "",
  },
];

export default function InfoBox() {
  return (
    <div className="bg-[#e7a324] w-full md:w-[800px] mx-5 shadow-xl p-4 md:p-6 flex flex-col justify-center rounded-xl">
      <div className="text-center font-bold text-2xl sm:text-4xl my-8">
        Why Participate in MonkyLand?
      </div>
      <Accordion
        type="single"
        collapsible
        className="w-full max-w-3xl mx-auto space-y-2"
      >
        {accordionItems.map((item) => (
          <AccordionItem
            key={item.value}
            value={item.value}
            className="border-b border-b-neutral-800 group"
          >
            <AccordionTrigger className="text-black text-lg md:text-xl hover:no-underline hover:opacity-70 transition-all duration-300 ease-out group-data-[state=open]:text-primary w-full flex justify-between items-center">
              <div className="text-left flex items-start gap-1">
                <div>{item.icon}</div> <div>{item.title}</div>
              </div>
              <ChevronDown className="h-6 w-6 shrink-0 transition-transform duration-300 group-data-[state=open]:rotate-180" />
            </AccordionTrigger>
            {item.content && (
              <AccordionContent className="text-gray-700 transition-all pl-7 duration-300 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95">
                {item.content}
              </AccordionContent>
            )}
          </AccordionItem>
        ))}
      </Accordion>
      <div className="flex justify-center my-4">
        <button className="btn-primary w-full sm:w-1/2">LEARN MORE</button>
      </div>
    </div>
  );
}
